services:
  db:
    image: mysql:latest
    container_name: mysql-escola
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: sistema_escolar

    ports:
      - "3306:3306"

    volumes:
      # Mapeia o script de inicialização
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql